spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    store-type: none
  messages:
    encoding: UTF-8
  output:
    ansi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/NOVEL_SERVICE?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: zz12zz
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
logging:
  level:
    org.hibernate.SQL: debug